apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: review-preview
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: review-preview
    spec:
      containers:
      - name: review-preview
        image: gcr.io/review-preview/review-preview:latest
        ports:
        - containerPort: 80
